### PR TITLE
[WIP] creating a project

### PR DESCRIPTION
**Pull request by AlissonSteffens**

### CODE REVIEW

**Comment by ballenwillis** [comment]
I do wonder, why did you take out the ReadMe that said it was my first game? haha

**Comment by ballenwillis** [comment]
Id didn't look at the code too much, but LET'S DO IT LIVE! hahaha

By the way, this is a very old (and practically dead) repository. The real repository is on @JoshuaCrotts profile because at the time of development he had no idea how to use github if it wasn't on his own profile for some reason. Isn't that correct, @JoshuaCrotts? haha

**Comment by AlissonSteffens** [comment]
@BWillis98  sorry, i've messed it up. just trying to make it run on NetBeans

**Comment by ballenwillis** [comment]
I'm just now realizing that that he actually forked his version from mine haha

**Comment by AlissonSteffens** [comment]
I'll let documentation and readme for later :v

**Comment by ballenwillis** [comment]
@AlissonSteffens , it's all good. Let's just merge it! haha I haven't seen this in years! Thank you for this!

**Comment by joshuacrotts** [comment]
Brandon is my superior.

**Comment by ballenwillis** [comment]
^

**Comment by joshuacrotts** [comment]
Brandon is my superior.

**Comment by ballenwillis** [comment]
m8 no you are not. Yous in my court now.

**Comment by joshuacrotts** [comment]
Brandon is my superior.

**Comment by ballenwillis** [comment]
Someone had to make God... so... I'm your God... God... haha

**Comment by AlissonSteffens** [comment]
Yeah, I was just clonning @JoshuaCrotts  project too :s 
obS: I'm really better now @JoshuaCrotts  :) and U? 👍

**Comment by joshuacrotts** [comment]
Brandon is my superior.

**Comment by ballenwillis** [comment]
No, he asked "Who" are you, not "How" lol. I don't think I know you either. And @JoshuaCrotts , the projects are SOOOO not the same lol

**Comment by AlissonSteffens** [comment]
image

**Comment by joshuacrotts** [comment]
Brandon is my superior.

**Comment by AlissonSteffens** [comment]
Sorry for the bad english :v

**Comment by joshuacrotts** [comment]
Brandon is my superior.

**Comment by AlissonSteffens** [comment]
Well, I'm a Brazilian CS student 👍

**Comment by joshuacrotts** [comment]
Brandon is my superior.

**Comment by ballenwillis** [comment]
@AlissonSteffens , how did you find this repository? lol

**Comment by AlissonSteffens** [comment]
Github search for Castlevania 
imgur-search

**Comment by ballenwillis** [comment]
That's dope that our project came up lol

**Comment by AlissonSteffens** [comment]
so... Should I fork @JoshuaCrotts 's fork, or stay there?

**Comment by AlissonSteffens** [comment]
I was thinking about to add some Agents based AI for this game 😃

**Comment by ballenwillis** [comment]
You can honestly do whatever you want lol. I barely remember this project anymore. I recommend building off of the much more updated @JoshuaCrotts one though. He's made one within the past year that's WAY better with graphics and code.

**Comment by AlissonSteffens** [comment]
Thanks

**Comment by ballenwillis** [comment]
I have no idea what I just merged tbh lol

**Comment by AlissonSteffens** [comment]
well, I'll create a PR at @JoshuaCrotts 's repo. ty everyone 👍

**Pull request merged**
